server:
    port: 8081
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: '**Ezeagbo166854**'
        url: jdbc:postgresql://localhost:5432/librarydb
        username: postgres

    application:
        name: SERVICE-PROVIDER-SERVICE
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5

management:
    security:
        enabled: false